package com.untamed.untamedbackend.notification;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    SESSION_RESCHEDULED,
    SESSION_CANCELLED,
    SESSION_DELAYED,
    ATTENDANCE_MARKED_PRESENT,
    ATTENDANCE_MARKED_ABSENT,
    REVIEW_AVAILABLE,
    GUIDE_REVIEW_RECEIVED,
    REFUND_REQUESTED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    GUIDE_SUSPENDED,
    GUIDE_REACTIVATED,
    SESSION_CANCELLED_REFUND_PENDING,
    REFUND_PROCESSED,
    REFUND_FAILED_REVIEW,
    REPORT_REVIEWED,
    SUSPENSION_APPEAL_REVIEWED,
    CHAT_MESSAGE,
    SYSTEM
}
