package com.untamed.untamedbackend.notification;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    SESSION_RESCHEDULED,
    SESSION_CANCELLED,
    SESSION_DELAYED,
    ATTENDANCE_MARKED_PRESENT,
    ATTENDANCE_MARKED_ABSENT,
    REVIEW_AVAILABLE,
    GUIDE_REVIEW_RECEIVED,
    REFUND_REQUESTED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    SYSTEM
}
