spring.application.name=UnTamed-backend
spring.mongodb.uri=mongodb+srv://mehdirokbani4:DcWWF25V94ZQiVlq@mehdi0.w1y43.mongodb.net/UnTamed
spring.mongodb.database=UnTamed

jwt.secret=Y+jH6CV->y6{eKutc@{{PmWBP|=-F^n,Zv%4S-CL.Q9
jwt.expiration=86400000
